name: devops app
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
 
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
 
    - name: List Files
      run: |
        echo "Terry is teaching"
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run tests with pytest
      run: |
        pytest
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
    - uses: actions/checkout@v4
 
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS}}
 
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "devops-exe"
        publish-profile: ${{ secrets.AUZRE_PUBLISH }}
        images: ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
       